
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/163vPf5U4pLnWvtTKXthi-OKqTxIK69C2
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

df = pd.read_csv("/content/AirQualityUCI (1).csv")

print(df.head())
print(df.shape)
print(df.columns)

print(df.info())
print(df.isnull().sum())
print("Duplicates:", df.duplicated().sum())
print(df.describe())

df = pd.read_csv("/content/AirQualityUCI (1).csv", sep=';')

# Drop the last two unnamed columns which are usually empty in this dataset
df = df.drop(columns=['Unnamed: 15', 'Unnamed: 16'], errors='ignore')

# The original line `X = df.drop("", axis=1)` caused a KeyError because the column "" does not exist.
# This also needs to be fixed as 'Air Quality Category' is not a direct column in the raw data.
# You need to define how to create 'Air Quality Category' or select a different target column.
# For now, X will contain all columns after initial cleanup.
X = df.copy()
# y = df["Air Quality Category"] # This column does not exist in the raw data

# Placeholder for y. Please define 'Air Quality Category' or choose another target column from df
y = pd.Series([0]*len(df)) # Temporary placeholder to avoid error, replace with actual target

X = X.select_dtypes(include="number")

encoder = LabelEncoder()
y = encoder.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)

sns.heatmap(cm, annot=True, fmt="d")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()
